# Generated by Django 4.0.10 on 2024-03-31 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_user', '0001_initial'),
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_address', models.CharField(default='street', max_length=255)),
                ('city', models.CharField(default='city', max_length=200)),
                ('state_province', models.CharField(default='state', max_length=200)),
                ('postal_code', models.CharField(default='postal_code', max_length=50)),
                ('country', models.CharField(default='country', max_length=200)),
                ('destination', models.CharField(max_length=100)),
                ('state', models.CharField(choices=[], default='state', max_length=50)),
            ],
            options={
                'db_table': 'tasks',
            },
        ),
        migrations.CreateModel(
            name='Trips',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_address', models.CharField(default='street', max_length=255)),
                ('city', models.CharField(default='city', max_length=200)),
                ('state_province', models.CharField(default='state', max_length=200)),
                ('postal_code', models.CharField(default='postal_code', max_length=50)),
                ('country', models.CharField(default='country', max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(default='lastname', max_length=255)),
                ('image', models.CharField(blank=True, max_length=255, null=True)),
                ('license', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=50)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_user.admin')),
                ('customer', models.ManyToManyField(to='customer.customer')),
            ],
        ),
    ]
