# Generated by Django 5.0.3 on 2024-03-19 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_from', models.CharField(max_length=100)),
                ('delivery_to', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tasks',
            },
        ),
        migrations.RenameField(
            model_name='driver',
            old_name='name',
            new_name='firstname',
        ),
        migrations.AddField(
            model_name='driver',
            name='lastname',
            field=models.CharField(default='lastname', max_length=255),
        ),
    ]
