# Generated by Django 5.0.3 on 2024-03-19 00:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_rename_name_customer_lastname_customer_birthday_and_more'),
        ('driver', '0002_tasks_rename_name_driver_firstname_driver_lastname'),
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardholder_name', models.CharField(max_length=100)),
                ('card_number', models.CharField(max_length=16)),
                ('expiration_date', models.DateField()),
                ('cvv_code', models.CharField(max_length=4)),
                ('billing_address', models.CharField(max_length=255)),
                ('card_type', models.CharField(max_length=50)),
                ('issuer', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=50)),
                ('default_card', models.BooleanField()),
            ],
            options={
                'db_table': 'card',
            },
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
                ('driver', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='driver.driver')),
            ],
            options={
                'db_table': 'transactions',
            },
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
