# Generated by Django 5.0.3 on 2024-03-19 00:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_rename_name_customer_lastname_customer_birthday_and_more'),
        ('payment', '0002_card_transactions_delete_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='issuer',
        ),
        migrations.AddField(
            model_name='card',
            name='customer',
            field=models.ForeignKey(default='customer-name', on_delete=django.db.models.deletion.CASCADE, to='customer.customer'),
            preserve_default=False,
        ),
    ]
