# Generated by Django 4.0.10 on 2024-03-31 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_address', models.CharField(default='street', max_length=255)),
                ('city', models.CharField(default='city', max_length=200)),
                ('state_province', models.CharField(default='state', max_length=200)),
                ('postal_code', models.CharField(default='postal_code', max_length=50)),
                ('country', models.CharField(default='country', max_length=200)),
                ('location', models.CharField(max_length=255)),
                ('destination', models.CharField(max_length=255)),
                ('order_notes', models.TextField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(choices=[('wood', 'Wood'), ('multiple commodities', 'Multiple Commodities '), ('food', 'Food'), ('glass', 'Glass'), ('furniture', 'Furinture'), ('plastic&rubber', 'Plastic and Rubber'), ('appliances', 'Appliances')], max_length=200)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pickup_time', models.DateTimeField()),
                ('pricing', models.BigIntegerField()),
                ('packing', models.BooleanField()),
                ('labor', models.BooleanField()),
                ('order_state', models.CharField(choices=[], max_length=200)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
            ],
            options={
                'db_table': 'orders',
            },
        ),
    ]
