# Generated by Django 4.0.10 on 2024-03-31 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='type',
            field=models.CharField(choices=[('food', 'Food'), ('appliances', 'Appliances'), ('furniture', 'Furinture'), ('multiple commodities', 'Multiple Commodities '), ('glass', 'Glass'), ('wood', 'Wood'), ('plastic&rubber', 'Plastic and Rubber')], max_length=200),
        ),
    ]
