# Generated by Django 5.0.3 on 2024-03-19 00:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_rename_name_customer_lastname_customer_birthday_and_more'),
        ('shipment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
                ('destination', models.CharField(max_length=255)),
                ('order_notes', models.TextField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(choices=[('plastic&rubber', 'Plastic and Rubber'), ('appliances', 'Appliances'), ('glass', 'Glass'), ('wood', 'Wood'), ('food', 'Food'), ('furniture', 'Furinture'), ('multiple commodities', 'Multiple Commodities ')], max_length=20)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pickup_from', models.CharField(max_length=100)),
                ('delivery_to', models.CharField(max_length=100)),
                ('pickup_time', models.DateTimeField()),
                ('pricing', models.BigIntegerField()),
                ('packing', models.BooleanField()),
                ('labor', models.BooleanField()),
                ('order_state', models.CharField(choices=[], max_length=1)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
            ],
            options={
                'db_table': 'orders',
            },
        ),
        migrations.DeleteModel(
            name='Shipment',
        ),
    ]
