# Generated by Django 4.0.10 on 2024-04-17 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='type',
            field=models.CharField(choices=[('wood', 'Wood'), ('furniture', 'Furinture'), ('plastic&rubber', 'Plastic and Rubber'), ('food', 'Food'), ('appliances', 'Appliances'), ('glass', 'Glass'), ('multiple commodities', 'Multiple Commodities ')], max_length=200),
        ),
    ]
