# Generated by Django 4.0.10 on 2024-04-17 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('driver', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('license', models.CharField(max_length=255)),
                ('registration_number', models.CharField(max_length=255)),
                ('driver', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='driver.driver')),
            ],
        ),
    ]
